#!/usr/bin/env ansible-playbook
---
- name: Main play
  hosts: all

  pre_tasks:
    - name: Check Ansible version
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.9', '>=')
        msg: The Ansible version is too old for this playbook

  tasks:
    - name: Execute apt update if the last one is more than 1 hour ago
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_pkg_mgr == "apt"

    - name: Install Linux kernel headers # Needed to build the vboxdrv kernel module
      become: true
      ansible.builtin.package:
        name: linux-headers-{{ ansible_kernel }}

    - name: Install VirtualBox
      ansible.builtin.include_role: { name: oefenweb.virtualbox }
      # noqa: var-naming[no-role-prefix]
      vars: { ansible_become: true }

    - name: Install Vagrant
      ansible.builtin.include_role: { name: dmotte.vagrant }
      # noqa: var-naming[no-role-prefix]
      vars: { ansible_become: true }
